убрал наследование, проверьте пожалуйста
avalon-dev-j110/laboratornaya-rabota-no1-evtifievAnatoliy pull request #2
Opened 2020-03-23 15:45 UTC by evtifievAnatoliy

убрал наследование в классе Passport, добавил метод toString в классе Passport.
Проверьте пожалуйста

2020-03-23 15:49 UTC, evtifievAnatoliy commented
Так же перенесена сущность birthDate из класса Passport, в класс Person. Изменены и добавлены конструкторы класса Person

2020-04-08 20:57 UTC, KolosovKD requested changes
Все очень прилично. Есть несоответствие в классе **Passport** между описанием класса в комментариях и содержимым.

2020-04-08 20:57 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/models/Passport.java
> +    public Passport(String passportNumber, String birthdayDate, String issureDate, String issure) {
Не используемый параметр **birthdayDate**

2020-04-08 20:57 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/models/Person.java
>      }
Используйте перегрузку конструкторов с помощью ключевого слова **this()**.
Конструктор с бОльшим количеством параметров первой строкой вызывает с помощью **this()** конструктор с меньшим количеством параметров, а потом просто дозаполняет оставшиеся незаполненными поля.

2020-04-08 20:57 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/models/Passport.java
>      private String issure;
ОБращайте внимание на комментарии. Предполагалось что в классе Passport будут все паспортные данные человека включая имя, фамилию, отчество, второе имя и т.д.

2020-04-10 15:20 UTC, merged

2020-04-12 17:44 UTC, konivex reviewed
Исправьте оставшееся замечание.

2020-04-12 17:44 UTC, konivex commented on src/ru/avalon/java/dev/j10/labs/models/Person.java
>      }
Замечание Кирилла Дмитриевича не исправлено. Исправьте.